### ISSUE TITLE
fetcher is undeclared 

### ISSUE THREAD

**Issue by sudosean** [loong/go-concurrency-exercises#20]
https://github.com/loong/go-concurrency-exercises/blob/master/0-limit-crawler/main.go#L26 fetcher is not declared

not sure how active  this  repo is anyore

**Comment by viktomas** [comment]
@sudosean If you didn't clone this project to your `$GOPATH` you might want to run `go mod init go-concurrency-exercises` in the repository root (the module name is arbitrary since you are not going to publish it)

**Comment by loong** [comment]
Thank you so much @viktomas for the workaround!

Merged this pull request https://github.com/loong/go-concurrency-exercises/pull/22, and we are finally making use of go modules 🎉
