### ISSUE TITLE
Invalid Slack link

### ISSUE THREAD

**Issue by azdaev** [loong/go-concurrency-exercises#24]
Hello! Your Slack link is invalid.

**Comment by loong** [comment]
Hi @azdaev thanks for pointing out! It seems to be a problem not only for us:
https://www.reddit.com/r/golang/comments/jobh3d/gopher_slack_invite/

Will update the link! I'm also considering to maybe switch to discord as the gopher discord seems to be more active than the gother slack 🤔

**Comment by loong** [comment]
Updated the docs!
